### PR TITLE
chore: [SETI-787] add secrets scan

### PR DESCRIPTION
**Pull request by kaofelix**

### CODE REVIEW

**Review by javigomez — APPROVED** [review]
Have you tried to add a leak to see how it works?

**Review by javigomez — COMMENTED** [review]
Oops 

Screenshot 2021-01-29 at 16 34 05

**Comment by javigomez** [comment]
We are running it twice for 1 PR:

Screenshot 2021-01-29 at 16 35 20

**Comment by therussiankid92** [comment]
Does this PR need something else?

**Pull request merged**
